ALTER DATABASE [RTLFlix] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [RTLFlix] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [RTLFlix] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [RTLFlix] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [RTLFlix] SET ARITHABORT OFF 
GO
ALTER DATABASE [RTLFlix] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [RTLFlix] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [RTLFlix] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [RTLFlix] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [RTLFlix] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [RTLFlix] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [RTLFlix] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [RTLFlix] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [RTLFlix] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [RTLFlix] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [RTLFlix] SET  DISABLE_BROKER 
GO
ALTER DATABASE [RTLFlix] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [RTLFlix] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [RTLFlix] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [RTLFlix] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [RTLFlix] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [RTLFlix] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [RTLFlix] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [RTLFlix] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [RTLFlix] SET  MULTI_USER 
GO
ALTER DATABASE [RTLFlix] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [RTLFlix] SET DB_CHAINING OFF 
GO
ALTER DATABASE [RTLFlix] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [RTLFlix] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
USE [RTLFlix]
GO
/****** Object:  Table [dbo].[Cast]    Script Date: 2019/04/01 08:26:42 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Cast](
	[CastIDPK] [int] IDENTITY(1,1) NOT NULL,
	[CastID] [int] NOT NULL,
	[Name] [nvarchar](50) NULL,
	[BirthDay] [datetime] NULL,
 CONSTRAINT [PK_Cast_1] PRIMARY KEY CLUSTERED 
(
	[CastIDPK] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[Show]    Script Date: 2019/04/01 08:26:42 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Show](
	[ShowID] [int] NOT NULL,
	[ShowName] [nvarchar](50) NULL,
 CONSTRAINT [PK_Show] PRIMARY KEY CLUSTERED 
(
	[ShowID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[ShowCast]    Script Date: 2019/04/01 08:26:42 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ShowCast](
	[ShowCastID] [int] NOT NULL,
	[ShowID] [int] NOT NULL,
	[CastID] [int] NOT NULL,
 CONSTRAINT [PK_ShowCast] PRIMARY KEY CLUSTERED 
(
	[ShowCastID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
USE [master]
GO
ALTER DATABASE [RTLFlix] SET  READ_WRITE 
GO